version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/modules/liberty"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/modules/payara-micro"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/modules/payara-server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/modules/quarkus"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/modules/testcontainers"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/modules/wildfly"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/sample-apps/everything-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/sample-apps/jaxrs-basicauth"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/sample-apps/jaxrs-json"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/sample-apps/jaxrs-mpjwt"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/sample-apps/jdbc-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/sample-apps/kafka-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/sample-apps/liberty-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/sample-apps/maven-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/sample-apps/payara-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/sample-apps/quarkus-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/sample-apps/wildfly-app"
    schedule:
      interval: "weekly"