version: 2

update_configs:
  - package_manager: "java:gradle"
    directory: "/core"
    update_schedule: "weekly"

  - package_manager: "java:gradle"
    directory: "/modules/testcontainers"
    update_schedule: "weekly"

  - package_manager: "java:gradle"
    directory: "/modules/liberty"
    update_schedule: "weekly"

  - package_manager: "java:gradle"
    directory: "/modules/payara-micro"
    update_schedule: "weekly"

  - package_manager: "java:gradle"
    directory: "/modules/payara-server"
    update_schedule: "weekly"