version: 2
updates:
# Github Actions

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

# Gradle

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    ignore:
      #Stablelize on Jakarta 10 and Microprofile 7
      - dependency-name: "jakarta.platform:jakarta.jakartaee-api"
        versions: [ "[10, 11)" ]
      - dependency-name: "org.eclipse.microprofile:microprofile"
        versions: [ "[7, 8)" ]

# Maven - sample-apps

  - package-ecosystem: maven
    directory: /sample-apps/maven-app
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /sample-apps/quarkus-app
    schedule:
      interval: daily