name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["is:bug"] #Verified - label exists
body:
- type: input
  id: os
  validations:
    required: true
  attributes: 
    label: System OS
    description: e.g. Linux, Windows, Mac
- type: input
  id: java
  validations:
    required: true
  attributes: 
    label: Java Version
    description: e.g. 8, 11
- type: dropdown
  id: microshed
  validations:
    required: true
  attributes: 
    label: Microshed Version
    description: What version of the Microshed Testing are you running using?
      - 0.9.2-SNAPSHOT (Locally built)
      - 0.9.1
      - 0.9
      - 0.8
      - 0.7.1
      - 0.7
      - 0.6.2
      - 0.6.1.1
      - 0.6.1
      - 0.6
      - 0.5
- type: textarea
  validations:
    required: true
  attributes:
    label: Describe the bug
    value: |
      > A clear and concise description of what the bug is.
- type: textarea
  validations:
    required: true
  attributes:
    label: To Reproduce
    value: |
      > Steps to reproduce the bug
- type: textarea
  validations:
    required: true
  attributes:
    label: Expected behavior
    value: |
      > A clear and concise description of what you expected to happen.
- type: textarea
  attributes:
    label: Additional context
    value: |
      > Add any other context about the problem here.
