name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["is:enhancement"] #Verified - label exists
body:
- type: textarea
  validations:
    required: true
  attributes:
    label: Is your feature request related to a problem?
    value: |
      > A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- type: textarea
  validations:
    required: true
  attributes:
    label: Describe the solution you'd like
    value: |
      > A clear and concise description of what you want to happen.
- type: textarea
  validations:
    required: true
  attributes:
    label: Describe alternatives you've considered
    value: |
      > A clear and concise description of any alternative solutions or features you've considered.
- type: textarea
  attributes:
    label: Additional context
    value: |
      > Add any other context or screenshots about the feature request here.
