#TODO When microProfileReactiveMessaging3.0 is released, use a non beta version!
FROM icr.io/appcafe/open-liberty:beta
COPY src/main/liberty/config /config/
ADD build/libs/myservice.war /config/apps/

